# -*- coding: utf-8 -*-
"""output_format.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L5lJxS8homLGeKeA_MlOIPX8-gSTT_Sp
"""

output = ""
def correct_soln(output):
  l = output.split(',')

  splits = [l[i].split(':') for i in range(len(l))]

  distinct = []
  distinct_values = []
  for j in range(-1,-len(splits)+1,-1):
    if splits[j][0] not in distinct:
      distinct.append(splits[j][0])
      distinct_values.append(splits[j])

  distinct_values.remove(distinct_values[0])
  return distinct_values

true_soln = correct_soln(output)

def make_vector(true_soln):
  out = str(true_soln)

  out_real = ''
  for i in range(len(out)):
    if out[i]=='[':
      out_real+='{'
      continue
    if out[i] == ']':
      out_real+='}'
      continue
    if out[i]=='\'':
      out_real+="\""
    else:
      out_real+=out[i]
  return out_real

cpp_vector = make_vector(true_soln)